# Site settings
title: 深夜食堂
tagline: 谁都无法赐予你未来，因为你，就是未来
email: jeremybaiit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
#  Hi, I’m a student from Soochow University. 
# I love being minimal and creative.
# baseurl: "/gaya" # the subpath of your site, e.g. /blog/
baseurl: ""
#url: "http://gayan.me" # the base hostname & protocol for your site
#url: "http://jeremybai.github.io"
#url: 127.0.0.1:4000
#留空便于本地调试
url: 
host: 127.0.0.1
port: 4000
production_url : http://jeremybai.github.io
logourl: /assets/images/logo.png # Site logo
author: "Jeremy Bai"
author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: jeremybai
    twitter: JeremyBai
    #facebook: jeremybai
    #gplus: +jeremybai
    # dribble: jeremybai
    # pinterest: jeremybai

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  # disqus_shortname: gaya-webcreate

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 

# Build settings
markdown: rdiscount

# Permalinks
#permalink:        pretty
permalink: /blog/:year/:month/:day/:title

# Pagination config
paginate: 7

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed

# Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
excerpt_separator: ""
